apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/seolman/homelab.git
    targetRevision: HEAD
    path: infra/overlays/prod/traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
