---
- name: Install cert-manager
  kubernetes.core.helm:
    name: cert-manager
    namespace: cert-manager
    create_namespace: true
    chart_ref: oci://quay.io/jetstack/charts/cert-manager
    chart_version: v1.19.2
    state: present
    wait: true
    values:
      crds:
        enabled: true
      extraArgs:
        - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
        - --dns01-recursive-nameservers-only=true
  run_once: true
  delegate_to: localhost

- name: cloudflare secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflare-api-token-secret
        namespace: cert-manager
      type: Opaque
      stringData:
        # api-token: 
  run_once: true
  delegate_to: localhost

- name: issuer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: cloudflare-clusterissuer
      spec:
        acme:
          email: tjfehdgns@gmail.com
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: cloudflare-clusterissuer-account-key
          solvers:
            - dns01:
                cloudflare:
                  apiTokenSecretRef:
                    name: cloudflare-api-token-secret
                    key: api-token
  run_once: true
  delegate_to: localhost
