apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-ingressroute
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`minio.seolman.dev`)
      services:
        - name: main-tenant-console
          port: 9090
    - kind: Rule
      match: Host(`s3.minio.seolman.dev`)
      services:
        - name: minio
          port: 80
  tls:
    secretName: minio-tls
