apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/minio
  - ./tenant.yaml

helmCharts:
  - name: operator
    repo: https://operator.min.io/
    releaseName: minio
    namespace: minio-system
    includeCRDs: true
    valuesFile: ./values.yaml
