apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/minio

helmCharts:
  - name: minio
    repo: https://charts.bitnami.com/bitnami
    version: 17.0.21
    releaseName: minio
    namespace: minio-system
    includeCRDs: true
