---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: storage-configuration
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    config.env: AgAaOUHFpCY5euvvgOXpMM91tBqn4toY55pC1cbLJn0nc/Q4GYem850izzoCAlyg2jwyThew2hfS671StvYci36FpdxupEjyEi6rxlzYgoeybDCmxbIP173Mcn1uWk7RC8gLYk6W46kX3YrxkBg/g87t2mpq/rWmw1u7q673jRHi92Thc8nb7/PEVUFaYWHXXvWBXqXNH5fYkBV2RgUhFQy9JCVNaB2Shdw6eGqOGW54Em3NoSyE0m5h1meqloi4UHhMEflYsr0HRSV0Z0gXD2f9ZwrKMx+H5G6tkYGdheXjB2ae25P+0PjGTdHsvC/9W8MUw6LEpelO/6E28C+FALrjyD/7bnlsnZxAZS7NU0F7xduHFw8huCj2vdd0klfVOgmivUm5eCCs2iDMZ7fhw7JCGYxOimBMIqrtnmumhpJxeFGL7sNnWGPLp1hMe8C26Jxuqk9LeSeKsCQ4ZCu3i39eH/tA3V0JxB8Y8tA1Cg6yBFW0Fot/QsGN92+a2uUshR/how/vh0LbuLX25qkV8weGgE1Bmw0mt8Fs81qqamoCsTPtIba3qMm7nX4Cn3hzq8bmZrZmmpW8KClzz3hiWw3ZDGkMsGo5NYkkcl68+7Gqda9kKRG6YEmuF5NRYVUvp6QtWTYjqxW35bnir0MwtiI1G3Kd21KA1zS0dr6aZd3k2rcok/vqizCN1WyYhkQLZrrr7ReQyn8w3lbkLXmA8gQ4MsrZGQXzIRKbn8V5JY4I7E9Vjv9SiETWejqkIrIcJclg6xXbTyoRdwUcM69XcfbF/cOr9g/bx/3/HaucanV0QNUsCnObIsWVW6uNvsjacmrP3Dm1LADCJ6df33WKUQjCuHkduDwC+8Bn8w6ZtoYUP2DtQ0luSqXuwONy5EuL
  template:
    metadata:
      name: storage-configuration
      namespace: database
    type: Opaque
