---
all:
  children:
    k3s_cluster:
      children:
        k3s_masters:
          hosts:
            pi1:
              ansible_host: 192.168.8.21
            pi2:
              ansible_host: 192.168.8.22
            pi3:
              ansible_host: 192.168.8.23
        k3s_workers:
          hosts:
            n100:
              ansible_host: 192.168.8.10
