apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/postgresql
  - ./namespace.yaml
  # - ./clusters.yaml

helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.io/charts/
    version: 0.27.0
    releaseName: cloudnative-pg
    namespace: cnpg-system
    includeCRDs: true
