apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/kube-prometheus-stack

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 81.0.0
    releaseName: prometheus-stack
    namespace: monitoring
    includeCRDs: true
