apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik-crds
    repo: https://traefik.github.io/charts
    version: 1.13.0
    releaseName: traefik-crds
    namespace: traefik-system

  - name: traefik
    repo: https://traefik.github.io/charts
    version: 38.0.1
    releaseName: traefik
    namespace: traefik-system
    valuesFile: ./traefik_values.yaml
