apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 38.0.1
    releaseName: traefik
    namespace: traefik-system
    includeCRDs: true
    valuesFile: ./values.yaml

resources:
  - ../../../base/traefik
  - ./ingressroute.yaml
  - ./certificate.yaml
