apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/traefik

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 38.0.1
    releaseName: traefik
    namespace: traefik-system
    valuesFile: ./traefik_values.yaml
