apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/traefik

helmCharts:
  - name: traefik
    releaseName: traefik
    namespace: traefik-system
    valuesFile: ./traefik_values.yaml
