apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./sealed_cloudflare_api_token.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.19.2
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
