apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manger
    repo: https://charts.jetstack.io
    version: 1.19.2
    namespace: cert-manager
    includeCRDs: true
