apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    repo: oci://ghcr.io/traefik/helm/traefik
    version: 38.0.1
    releaseName: traefik
    namespace: traefik-system
