apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ingressroute
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`nginx.seolman.dev`)
      services:
        - name: nginx-service
          port: 80
  tls:
    secretName: nginx-tls
