apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ingressroute
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`nginx.homelab.local`)
      services:
        - name: nginx-service
          port: 80
